targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          include:
            - lib/**.dart
      go_router_builder:
        generate_for:
          include:
            - lib/app/router/**.dart
