arb-dir: lib/app/localisation/l10n
template-arb-file: app_en.arb
output-dir: lib/app/localisation/generated
output-localization-file: app_localizations.dart
output-class: AppLocalizations
nullable-getter: false
use-escaping: true
